export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'
export const LOGOUT = 'LOGOUT'

export const ERROR = 'ERROR'
export const SHOW_PROFILE_MODAL = 'SHOW_PROFILE_MODAL'
export const ORIENTATION_CHANGE = 'ORIENTATION_CHANGE'

export const MAIN_CARD_INDEX = 'MAIN_CARD_INDEX'

export const DRAWER_VIEW = 'DRAWER_VIEW'
export const DRAWER_OPEN_STATUS = 'DRAWER_OPEN_STATUS'

export const TOGGLE_ALL_ON = 'TOGGLE_ALL_ON'
export const TOGGLE_ALL_OFF = 'TOGGLE_ALL_OFF'
export const SET_MESSAGE_USER_STATUS = 'SET_MESSAGE_USER_STATUS'
export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'
export const RESTORE_SETTINGS = 'RESTORE_SETTINGS'
export const PROCESSING_TOPIC = 'PROCESSING_TOPIC'
export const PROCESSING_SUB_TOPIC = 'PROCESSING_SUB_TOPIC'

export const UPDATING_USER = 'UPDATING_USER'
export const UPDATING_USER_SUCCESS = 'UPDATING_USER_SUCCESS'


export const SHOW_RESET_PASSWORD = 'SHOW_RESET_PASSWORD'
export const LOGIN_MODAL_CHANGED = 'LOGIN_MODAL_CHANGED'
export const LOGIN_MODAL_HIDE = 'LOGIN_MODAL_HIDE'
export const LOGIN_MODAL = 'LOGIN_MODAL'
export const REGISTER_MODAL = 'REGISTER_MODAL'
export const FORGOT_PASSWORD_MODAL = 'FORGOT_PASSWORD_MODAL'
export const NEED_AUTHENTICATION = 'NEED_AUTHENTICATION'


export const BEER_MENU_SECTION = 'BEER_MENU_SECTION'
export const BEER_MENU_LOADING = 'BEER_MENU_LOADING'
export const BEER_MENU_LOADING_END = 'BEER_MENU_LOADING_END'
export const BEER_MENU_SUCCESS = 'BEER_MENU_SUCCESS'
export const BEER_MENU_FAIL = 'BEER_MENU_FAIL'
export const BEER_MENU_SECTION_BEERS = 'BEER_MENU_SECTION_BEERS'

export const FOOD_TRUCKS_MENU_LOADING = 'FOOD_TRUCKS_MENU_LOADING'
export const FOOD_TRUCKS_MENU_SUCCESS = 'FOOD_TRUCKS_MENU_SUCCESS'
export const FOOD_TRUCKS_MENU_FAIL = 'FOOD_TRUCKS_MENU_FAIL'

export const RESTAURANTS_MENU_LOADING = 'RESTAURANTS_MENU_LOADING'
export const RESTAURANTS_MENU_SUCCESS = 'RESTAURANTS_MENU_SUCCESS'
export const RESTAURANTS_MENU_FAIL = 'RESTAURANTS_MENU_FAIL'

export const EVENTS_MENU_LOADING = 'EVENTS_MENU_LOADING'
export const EVENTS_MENU_SUCCESS = 'EVENTS_MENU_SUCCESS'
export const EVENTS_MENU_FAIL = 'EVENTS_MENU_FAIL'


export const DASHBOARD_CARDS_UPDATED = 'DASHBOARD_CARDS_UPDATED'
export const OPENED_NOTIFICATION = 'OPENED_NOTIFICATION'
export const CLEAR_OPENED_NOTIFICATION = 'CLEAR_OPENED_NOTIFICATION'
export const CLIENT_CONFIG_RECEIVED = 'CLIENT_CONFIG_RECEIVED'
