const BLACK = '#1A1919'
const RED = '#985B5B'
const LIGHT_RED = '#A91E22'
const BLUE = '#5B7498'
const WHITE = '#F8F5F5'
const TRUE_WHITE = '#FFF'
const LIGHT_GREY = '#E3E3E3'
const DRAWER_WHITE = '#FFFDFD'
const CARD_BACKGROUND = '#EDEDED'
const TRANSPARENT = '#0000'
const DARK_GREY = '#646161'

export default { BLACK, RED, LIGHT_RED, BLUE, WHITE, TRUE_WHITE, DRAWER_WHITE, TRANSPARENT, DARK_GREY, LIGHT_GREY, CARD_BACKGROUND }